In [3]:
import nltk
from nltk.tokenize import word_tokenize

In [5]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [6]:
tokens = word_tokenize("Hello World!, This is a dog.")
print(tokens)


words=[word for word in tokens if word.isalpha()]
print(words)

['Hello', 'World', '!', ',', 'This', 'is', 'a', 'dog', '.']
['Hello', 'World', 'This', 'is', 'a', 'dog']


In [7]:
from nltk.corpus import stopwords
print(stopwords.words('english')[:20])

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [11]:
from tensorflow.keras.preprocessing.text import *
print(text_to_word_sequence("This is a dog.")

['th', 's ', 's a dog']


* 중복 처리
* 우선순위는 중복이 많을수록 높다

In [13]:
t=Tokenizer()
text="""Deep learning is part of a broader family of machine learning methods base on 
artificial neural networks with representation learning"""
t.fit_on_texts([text])
print("단어 집합 : ",t.word_index)

단어 집합 :  {'learning': 1, 'of': 2, 'deep': 3, 'is': 4, 'part': 5, 'a': 6, 'broader': 7, 'family': 8, 'machine': 9, 'methods': 10, 'base': 11, 'on': 12, 'artificial': 13, 'neural': 14, 'networks': 15, 'with': 16, 'representation': 17}


## [0]을 붙여주는 이유
= t.texts_to_sequences([text])가 2차원 리스트이기 때문이다.

In [15]:
seq = t.texts_to_sequences([text])[0]
print(text,"->",seq)

Deep learning is part of a broader family of machine learning methods base on 
artificial neural networks with representation learning -> [3, 1, 4, 5, 2, 6, 7, 8, 2, 9, 1, 10, 11, 12, 13, 14, 15, 16, 17, 1]


In [17]:
seq2=t.texts_to_sequences([text])

[[3, 1, 4, 5, 2, 6, 7, 8, 2, 9, 1, 10, 11, 12, 13, 14, 15, 16, 17, 1]]

* text_to_word_sequence <- 토큰화
* fits_on_texts <- 단어 사전 생성
* texts_tosequences <- 정수 인코딩
* pad_sequences <- 입력값 크기 통일

In [18]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [19]:
X=pad_sequences([[7,8,9],[1,2,3,4,5],[7]],maxlen=3,padding='pre')
print(X)

[[7 8 9]
 [3 4 5]
 [0 0 7]]


pad_sequences(sequences, maxlen=None, padding='pre', truncating='pre',value=0.0)
* sequences = 패딩이 수행되는 시퀀스 데이터
* maxlen = 샘플의 최대 길이
* padding = 'pre' 이면 앞에서 0을 채우고 'post'이면 뒤에 0을 채운다